// Rhythm generation on a step grid.
//
// A pattern is a flat array of booleans, one per step, plus per-step velocity.
// 16 steps = one bar of 4/4 in sixteenth notes.
//
// Kit pieces are generated by *role*, not by name: anything that behaves like a
// hi-hat is generated like a hi-hat. That is what lets the kit grow — a shaker
// and a ride join the "hats" role and immediately know how to play themselves.

import { chance, pick, randInt, shuffle } from '../rng.js';

/**
 * General MIDI drum notes, channel 10, in kit order.
 *
 * `role` decides how a piece writes its own part:
 *   low       the foundation — the downbeat is its own
 *   backbeat  2 and 4
 *   hats      a steady subdivision
 *   offbeat   the &s between the beats
 *   perc      sparse syncopation, sprinkled off the grid's strong points
 *   clave     a fixed son-clave-shaped cell
 *   fill      quiet until the end of the phrase, then a run
 *   accent    one hit, at the top
 */
export const TRACKS = [
  { id: 'kick', label: 'Kick', note: 36, role: 'low' },
  { id: 'snare', label: 'Snare', note: 38, role: 'backbeat' },
  { id: 'clap', label: 'Clap', note: 39, role: 'backbeat' },
  { id: 'rim', label: 'Rim', note: 37, role: 'perc' },
  { id: 'tom', label: 'Tom', note: 45, role: 'fill' },
  { id: 'conga', label: 'Conga', note: 63, role: 'perc' },
  { id: 'hat', label: 'Closed hat', note: 42, role: 'hats' },
  { id: 'openhat', label: 'Open hat', note: 46, role: 'offbeat' },
  { id: 'ride', label: 'Ride', note: 51, role: 'hats' },
  { id: 'crash', label: 'Crash', note: 49, role: 'accent' },
  { id: 'shaker', label: 'Shaker', note: 70, role: 'hats' },
  { id: 'tamb', label: 'Tambourine', note: 54, role: 'offbeat' },
  { id: 'cowbell', label: 'Cowbell', note: 56, role: 'perc' },
  { id: 'woodblock', label: 'Woodblock', note: 76, role: 'clave' },
  { id: 'clave', label: 'Clave', note: 75, role: 'clave' },
  { id: 'triangle', label: 'Triangle', note: 81, role: 'accent' },
];

export const RHYTHM_STYLES = [
  { id: 'euclid', label: 'Euclidean', hint: 'Pulses spread as evenly as possible across the bar.' },
  { id: 'backbeat', label: 'Backbeat', hint: 'Kick on the floor, snare on 2 and 4.' },
  { id: 'chance', label: 'Pure chance', hint: 'Every step is a coin flip weighted by density.' },
  { id: 'cutup', label: 'Cut-up', hint: 'Generate a bar, then chop it into strips and shuffle.' },
  { id: 'polyrhythm', label: 'Polyrhythm', hint: 'Each piece gets its own pulse count, so the parts drift against each other.' },
];

/** The 3-2 son clave, as sixteenths. Every Latin-adjacent groove starts here. */
const SON_CLAVE = [0, 3, 6, 10, 12];

/** Pieces that make sense together, for the "surprise me" kit. */
const KIT_GROUPS = [
  { pick: [1, 1], from: ['snare', 'clap'] },
  { pick: [1, 1], from: ['hat', 'ride', 'shaker'] },
  { pick: [0, 2], from: ['openhat', 'tamb', 'rim', 'conga', 'cowbell'] },
  { pick: [0, 1], from: ['woodblock', 'clave'] },
  { pick: [0, 1], from: ['tom', 'crash', 'triangle'] },
];

/**
 * Euclidean rhythm (Bjorklund): distribute `pulses` over `steps` as evenly as
 * possible. This is the pattern behind a huge amount of world percussion.
 *
 * @param {number} steps
 * @param {number} pulses
 * @param {number} [rotation]
 * @returns {boolean[]}
 */
export function euclidean(steps, pulses, rotation = 0) {
  const n = Math.max(0, Math.floor(steps));
  const k = Math.min(n, Math.max(0, Math.floor(pulses)));
  const out = new Array(n).fill(false);
  if (n === 0 || k === 0) return out;
  // Bresenham formulation — same result as Bjorklund, far less code.
  for (let i = 0; i < n; i++) {
    out[i] = Math.floor((i * k) / n) !== Math.floor(((i - 1) * k) / n);
  }
  if (!rotation) return out;
  const r = ((rotation % n) + n) % n;
  return out.slice(r).concat(out.slice(0, r));
}

/** Chops a pattern into strips of whole beats and reshuffles them. */
export function cutUpPattern(pattern, rng, stepsPerBeat = 4) {
  const strips = [];
  for (let i = 0; i < pattern.length; i += stepsPerBeat) {
    strips.push(pattern.slice(i, i + stepsPerBeat));
  }
  return shuffle(rng, strips).flat().slice(0, pattern.length);
}

/** The role a kit piece plays, for anything that needs to ask. */
export function trackRole(id) {
  return TRACKS.find((t) => t.id === id)?.role || 'perc';
}

/**
 * A plausible random kit: always a kick, always something on 2 and 4, always
 * something keeping time, then a couple of extras. Better than picking from
 * sixteen checkboxes uniformly, which mostly gives you three cowbells.
 *
 * @param {() => number} rng
 * @returns {string[]} track ids, in kit order
 */
export function randomKitPieces(rng) {
  const chosen = new Set(['kick']);
  for (const group of KIT_GROUPS) {
    const [min, max] = group.pick;
    const count = randInt(rng, min, max);
    for (const id of shuffle(rng, group.from).slice(0, count)) chosen.add(id);
  }
  return TRACKS.filter((t) => chosen.has(t.id)).map((t) => t.id);
}

/**
 * Generates a full kit pattern.
 *
 * @param {object} opts
 * @param {() => number} opts.rng
 * @param {number} [opts.steps] steps per bar (16 = sixteenths in 4/4)
 * @param {number} [opts.bars]
 * @param {string} [opts.style] one of RHYTHM_STYLES
 * @param {number} [opts.density] 0..1 overall busyness
 * @param {number} [opts.variation] 0..1 how much bar 2+ drifts from bar 1
 * @param {string[]} [opts.trackIds] which kit pieces to include
 * @returns {{steps: number, bars: number, tracks: Array<{id: string, label: string, note: number, role: string, pattern: boolean[], velocities: number[]}>}}
 */
export function generateRhythm(opts) {
  const {
    rng,
    steps = 16,
    bars = 2,
    style = 'euclid',
    density = 0.5,
    variation = 0.25,
    trackIds = ['kick', 'snare', 'hat'],
  } = opts;

  const total = steps * bars;
  const silent = () => new Array(steps).fill(false);

  const tracks = TRACKS.filter((t) => trackIds.includes(t.id)).map((track) => {
    const bar = generateBar(track.role, { rng, steps, style, density });
    const pattern = [];
    for (let b = 0; b < bars; b++) {
      // A crash belongs at the top of the phrase and a tom fill at the bottom
      // of it, so those two roles are placed against the phrase, not the bar.
      let source;
      if (track.role === 'accent') source = b === 0 ? bar : silent();
      else if (track.role === 'fill') source = b === bars - 1 ? bar : silent();
      else source = b === 0 ? bar : mutate(bar, rng, variation);
      pattern.push(...source);
    }
    return {
      ...track,
      pattern: pattern.slice(0, total),
      velocities: pattern.slice(0, total).map((on, i) => (on ? accentFor(i, steps, rng) : 0)),
    };
  });

  return { steps, bars, tracks };
}

function generateBar(role, { rng, steps, style, density }) {
  const stepsPerBeat = Math.max(1, Math.round(steps / 4));
  const bar = new Array(steps).fill(false);

  // Two roles write the same part whatever the style is asked for: a crash is a
  // crash, and a clave is a clave.
  if (role === 'accent') {
    bar[0] = true;
    return bar;
  }
  if (role === 'clave') {
    const scale = steps / 16;
    for (const step of SON_CLAVE) {
      const at = Math.round(step * scale);
      if (at < steps) bar[at] = true;
    }
    // At low density it thins out to the 3 side of the clave alone.
    if (density < 0.35) for (let i = Math.floor(steps / 2); i < steps; i++) bar[i] = false;
    return bar;
  }
  if (role === 'fill') {
    // A run over the last beat, getting busier as density goes up.
    const from = Math.max(0, steps - Math.max(2, Math.round(stepsPerBeat * (0.5 + density))));
    for (let i = from; i < steps; i++) bar[i] = chance(rng, 0.45 + density * 0.5);
    if (!bar.some(Boolean)) bar[steps - stepsPerBeat] = true;
    return bar;
  }

  if (style === 'polyrhythm') {
    // Pulse counts that do not divide the bar, so the parts pull apart and only
    // line up again at the top.
    const counts = role === 'low' ? [3, 5] : role === 'hats' ? [7, 9, 11] : [3, 5, 7];
    const pulses = Math.min(steps, Math.round(pick(rng, counts) * (0.6 + density * 0.8)));
    const out = euclidean(steps, Math.max(2, pulses), randInt(rng, 0, steps - 1));
    if (role === 'low') out[0] = true;
    return out;
  }

  if (style === 'backbeat') {
    if (role === 'low') {
      bar[0] = true;
      bar[Math.floor(steps / 2)] = true;
      if (chance(rng, density)) bar[randInt(rng, 1, steps - 1)] = true;
    } else if (role === 'backbeat') {
      bar[stepsPerBeat] = true;
      bar[stepsPerBeat * 3] = true;
      if (chance(rng, density * 0.4)) bar[randInt(rng, 0, steps - 1)] = true;
    } else if (role === 'offbeat') {
      for (let i = Math.round(stepsPerBeat / 2); i < steps; i += stepsPerBeat) bar[i] = true;
    } else if (role === 'perc') {
      for (let i = 0; i < steps; i++) {
        if (i % stepsPerBeat !== 0) bar[i] = chance(rng, density * 0.35);
      }
    } else {
      const every = density > 0.66 ? 1 : density > 0.33 ? 2 : 4;
      for (let i = 0; i < steps; i += every) bar[i] = true;
    }
    return bar;
  }

  if (style === 'chance') {
    const bias = role === 'low' ? 0.7 : role === 'hats' ? 1.2 : role === 'perc' ? 0.5 : 0.8;
    const out = Array.from({ length: steps }, (_, i) => {
      // Downbeats are likelier than off-steps, or it turns to soup.
      const onBeat = i % stepsPerBeat === 0 ? 1.6 : 0.6;
      return chance(rng, Math.min(0.95, density * bias * onBeat));
    });
    if (role === 'low') out[0] = true;
    return out;
  }

  if (style === 'cutup') {
    const seed = generateBar(role, { rng, steps, style: 'euclid', density });
    const cut = cutUpPattern(seed, rng, stepsPerBeat);
    if (role === 'low' && !cut.some(Boolean)) cut[0] = true;
    return cut;
  }

  // Euclidean, with a pulse count scaled by density and the piece's role.
  const range = {
    low: [2, Math.round(steps * 0.55)],
    backbeat: [1, Math.round(steps * 0.4)],
    hats: [Math.round(steps * 0.25), steps],
    offbeat: [1, Math.round(steps * 0.5)],
    perc: [1, Math.round(steps * 0.45)],
  }[role] || [1, Math.round(steps * 0.4)];
  const pulses = Math.max(1, Math.round(range[0] + (range[1] - range[0]) * density));
  const rotation = role === 'backbeat'
    ? pick(rng, [0, Math.round(steps / 4)])
    : role === 'offbeat'
      ? Math.round(stepsPerBeat / 2)
      : role === 'perc'
        ? randInt(rng, 0, stepsPerBeat)
        : 0;
  const out = euclidean(steps, pulses, rotation);
  if (role === 'low') out[0] = true;
  return out;
}

function mutate(bar, rng, amount) {
  return bar.map((on, i) => {
    if (i === 0) return on;
    return chance(rng, amount * 0.5) ? !on : on;
  });
}

function accentFor(index, steps, rng) {
  const stepsPerBeat = Math.max(1, Math.round(steps / 4));
  const local = index % steps;
  const base = local === 0 ? 118 : local % stepsPerBeat === 0 ? 100 : 78;
  return Math.max(30, Math.min(127, base + randInt(rng, -8, 8)));
}

/**
 * Converts a step index into a time offset in seconds. Swing delays every
 * other step, which is what turns a straight sixteenth grid into a shuffle.
 *
 * @param {number} step
 * @param {number} secondsPerStep
 * @param {number} [swing] 0 = straight, 1 = maximum drag (triplet feel ≈ 0.66)
 */
export function stepTime(step, secondsPerStep, swing = 0) {
  const offset = step % 2 === 1 ? secondsPerStep * swing * 0.5 : 0;
  return step * secondsPerStep + offset;
}
